add extension.json
miraheze/YouTube pull request #1
Opened 2016-11-19 17:34 UTC by ImBoPhil

i'm not sure if this can be done

2016-11-28 17:11 UTC, MacFan4000 requested changes

2016-11-28 17:11 UTC, LegoFan4000 commented on extension.json
> +		"YouTube": "YouTube.class.php"
Remove the .class please

2016-11-28 17:13 UTC, ImBoPhil commented
@LegoFan4000 Being discussed on IRC with Southparkfan. Replacing .class file isn't the solution according to him.

2016-11-29 23:27 UTC, MacFan4000 commented
I updated youtube to the latest version in #2

2016-11-30 20:10 UTC, closed without merging